spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_ticket
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
  application:
    name: ms-ticket-manager

server:
  port: 8081

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

logging:
  level:
    org.springframework:
      web: DEBUG
      orm.jpa: DEBUG
      sql: DEBUG
    feign: DEBUG



# Documentação OpenAPI/Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

# Configuração de comunicação com ms-event-manager
services:
  event-manager:
    url: http://localhost:8080/api/v1

