spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/db_ticket
  application:
    name: ms-ticket-manager

server:
  port: 8081

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

logging:
  level:
    org.springframework:
      web: DEBUG
      data.mongodb: DEBUG
    feign: DEBUG

# Documentação OpenAPI/Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

# Configuração de comunicação com ms-event-manager
services:
  event-manager:
    url: http://localhost:8080/api/v1
